apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "elasticsearch.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "elasticsearch.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: {{ template "elasticsearch.name" . }}
    role: client
spec:
  serviceName: "data-service"
  replicas: {{ .Values.elasticsearchConfig.workerNodes }}
  selector:
    matchLabels:
      component: {{ template "elasticsearch.name" . }}
  template:
    metadata:
      name: {{ template "elasticsearch.name" . }}
      labels:
        component: {{ template "elasticsearch.name" . }}
        role: client
      annotations:
        networks: '[
        { "name": "{{ .Values.networks.overlay }}" }
      ]'
    spec:
      containers:
      - name: es-client
        image: {{ .Values.images.elasticsearch }}
        securityContext:
          runAsUser: {{ .Values.elasticsearchConfig.runAsUser }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          value: {{ .Values.elasticsearchConfig.env.clustername }}
        - name: NODE_MASTER
          value: "false"
        - name: NETWORK_HOST
          value: _eth0_,_lo_
        - name: ES_JAVA_OPTS
          value: "{{ .Values.elasticsearchConfig.env.javaopts }}"
        - name: DISCOVERY_SERVICE
          value: es-discovery
        ports:
        - name: http-9200
          containerPort: 9200
        - name: tcp-9300
          containerPort: 9300
        resources:
          requests:
            cpu: "{{ .Values.elasticsearchConfig.requests.cpu }}"
            memory: "{{ .Values.elasticsearchConfig.requests.memory }}"
          limits:
            cpu: "{{ .Values.elasticsearchConfig.limits.cpu }}"
            memory: "{{ .Values.elasticsearchConfig.limits.memory }}"
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: esdata
        - mountPath: /usr/share/elasticsearch/config/jvm.options
          subPath: jvm.options
          name: elasticsearch-jvm
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
          name: elasticsearch-config
        {{- if .Values.snapshotConfig.enabled }}
        - mountPath: /var/EDCOP/snapshots
          name: elasticsearch-snapshot
        {{- end }}

      volumes:
      - name: esdata
        hostPath:
          path: {{ .Values.volumes.data }}
      - name: elasticsearch-jvm
        configMap:
          name: {{ template "elasticsearch.fullname" . }}-jvm
      - name: elasticsearch-config
        configMap:
          name: {{ template "elasticsearch.fullname" . }}-config
      {{- if .Values.snapshotConfig.enabled }}
      - name: elasticsearch-snapshots
        persistentVolumeClaim:
          claimName: {{ template "elasticsearch.name" . }}-snapshots
      {{- end }}
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      nodeSelector:
        nodetype: {{ .Values.nodeSelector.client }}
