apiVersion: v1
kind: Service
metadata:
  name: es-discovery
  namespace: {{ .Values.namespace }}
  labels:
    component: {{ template "elasticsearch.name" . }}
    role: master
spec:
  ports:
  - name: tcp-9300
    protocol: TCP
    port: 9300 
    targetPort: 9300
  - name: tcp-9200
    protocol: TCP
    port: 9200
    targetPort: 9200
  selector:
    component: {{ template "elasticsearch.name" . }}
    role: master
  clusterIP: None
