apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "elasticsearch.fullname" . }}-post-installs-job
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "elasticsearch.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  template:
    metadata:
      name: {{ template "elasticsearch.name" . }}-post-installs
      annotations:
        "helm.sh/hook": "post-install"  # Run after all other services start
        networks: '[
        { "name": "{{ .Values.networks.overlay }}" }
      ]'
    spec:
      containers:
      - name: post-installs
        image: {{ .Values.images.runner }}
        imagePullPolicy: Always
        command: ["/post-installs.sh"]
        volumeMounts:
        - name: post-installs-script
          mountPath: /post-installs.sh
          subPath: post-installs.sh
      volumes:
      - name: post-installs-script
        configMap:
          name: {{ template "elasticsearch.fullname" . }}-post-installs-script
          defaultMode: 0744
      restartPolicy: OnFailure
