{{- if .Values.snapshotConfig.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "elasticsearch.fullname" . }}-snapshot
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "elasticsearch.name" . }}-snapshot
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  schedule: "{{ .Values.snapshotConfig.cronjob_schedule }}"
  successfulJobsHistoryLimit: {{ .Values.snapshotConfig.successfulJobsLimit }}
  failedJobsHistoryLimit: {{ .Values.snapshotConfig.failedPodsLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ template "elasticsearch.name" . }}-snapshot
          annotations:
            networks: '[
            { "name": "{{ .Values.networks.overlay }}" }
          ]'
        spec:
          containers:
          - name: snapshot
            image: {{ .Values.images.runner }}
            imagePullPolicy: Always
            command: ["/snapshot.sh"]
            volumeMounts:
              - name: snapshot-script
                mountPath: /snapshot.sh
                subPath: snapshot.sh
          volumes:
          - name: snapshot-script
            configMap:
              name: {{ template "elasticsearch.fullname" . }}-snapshot-script
              defaultMode: 0744
          restartPolicy: OnFailure 
{{- end -}}
